### VALUES YOU SHOULD CHANGE ###

# GENERAL SITE SETTINGS
# title: This will be displayed as the website's name in your browser tab.
title: Bryce Kinsey
# description: This will be meta HTML tag content. This can be ignored.
description: Bryce Kinsey's personal website powered by Jekyll.
# baseurl: The subpath of your site
# > set this to "", if you renamed the repository to <user>.github.io
baseurl: ""

# LANDING PAGE
# username: This will displayed on the landing page as your name.
username: Bryce Kinsey
# typing_text: This will be typed before 'scroll down for more'.
# > set this to your job title, e.g. Fullstack Developer
typing_text: "Cloud Engineer and Information Technology Professional"
# email: Your E-Mail address for the email button.
email: bryce@brycekinsey.com
# For every social button you want to display, set your username or userid
# If you do not use one of the following websites, then leave it empty
linkedin_username: bryce-kinsey
youtube_username: 
github_username: brycekinsey
codepen_username: 
dev_username: 
twitter_username:

# ABOUT ME SECTION
# show_aboutme_card:
# > setting this to true, will display the About Me section
# > setting this to false, will omit the About Me section
show_aboutme_card: true
# about_me_title: The will be displayed as the title in the About Me section
about_me_title: About Me
# about_me_description: This will be displayed under the title.
about_me_description: "Hello! I am Bryce, a well-rounded IT professional with a robust track record in managed services, systems administration, and cloud engineering/architecture (Azure). My drive is rooted in delivering service and leadership that not only meets but transcends industry expectations and organizational standards.

With meticulous attention to detail and an enduring passion for excellence, I excel in crafting and implementing goal-oriented IT strategies, complying with the latest industry guidelines. My standout abilities reside in developing and deploying robust solutions to identify and rectify system issues swiftly. As a creative problem solver and out-of-the-box thinker, I bring exceptional leadership, communication, relationship-building, and analytical skills to the table.

Throughout my professional journey, I have shown consistent dedication as a resourceful and result-oriented professional. My accomplishments range from successfully steering diverse technical projects from ideation to completion, adhering to defined scope, timeframe, and quality parameters. Additionally, I have proven expertise in integrating new systems into existing ones, installing hardware, standing up software solutions, and documenting system/process changes. I firmly believe that my progressive career trajectory can contribute to achieving an organization's core objectives. I am always enthusiastic about undertaking new challenges and opportunities that allow me to utilize my technical skills and experiences at a strategic level.

Living in Georgia, with my lovely wife and our energetic Pomeranian, my life outside of work includes enjoying time with family, community service through local churches, playing basketball, and tinkering in my home lab. If you're interested in discussing how my experiences can benefit your organization or if you'd like to chat about the latest trends in technology, don't hesitate to connect!"

# SKILLS SECTION
# show_skills_card:
# > setting this to true, will display the Skills section
# > setting this to false, will omit the Skills section
show_skills_card: false
# about_me_title: The will be displayed as the title in the Skills section
skills_title: Skills

# TIMELINE SECTION
# show_timeline_card:
# > setting this to true, will display the Timeline section
# > setting this to false, will omit the Timeline section
show_timeline_card: true
# timeline_title: The will be displayed as the title in the Timeline section
timeline_title: Education & Experience
# cv_download_link: The link where you host your cv.
# > e.g. you share your cv on your dropbox, then add the dropbox link here
cv_download_link: https://brycekinsey-my.sharepoint.com/:b:/p/bryce/ETWaRU-WLI5KlqeVLiQvWWEBANvcf8LyGcU80zKDZcng6A?e=KLZTeX

# PROJECTS SECTION
# show_projects_card:
# > setting this to true, will display the Projects section
# > setting this to false, will omit the Projects section
show_projects_card: true
# show_projects:
# > setting this to true, will display your listed projects in _data/projects.yml
# > setting this to false, will omit your listed projects
show_projects: false
# projects_title: The will be displayed as the title of your projects
projects_title: Personal Projects
# show_os_projects:
# > setting this to true, will display your public projects on github
# > setting this to false, will omit your public projects on github
show_os_projects: true
# os_projects_title: The will be displayed as the title of your open source projects
os_projects_title: Open Source Projects

# CONTACT SECTION
# show_contact_card:
# > setting this to true, will display the Contact section
# > setting this to false, will omit the Contact section
show_contact_card: true
# contact_title: The will be displayed as the title in the Contact section
contact_title: Contact
# contact_description: This will be displayed under the title.
contact_description: If you have any questions, comments, or business inquiries, please feel free to reach out to me. I would be more than happy to connect with you, so please don’t hesitate to get in touch using one of the below methods!

# GITHUB-METADATA
# Set this to your forked repository
# > e.g. <user>/<user>.github.io
repository: brycekinsey/brycekinsey.github.io
projects:
  # sortby:
  # > set this to pushed, if you want to sort your github repositories by time.
  # > set this to stars, if you want to sort your github repositories by stars.
  sort_by: pushed
  exclude:
    # archived:
    # > setting this to true, will exclude archived repositories
    # > setting this to false, will also display archived repositories
    archived: false
    # forks:
    # > setting this to true, will exclude forked repositories
    # > setting this to false, will also display forked repositories
    forks: false
    # projects: A list of the repository names you want to exclude from the listing.
    projects:
    # - repo1-to-be-excluded
    # - repo2-to-be-excluded

# GOOGLE-ANALYTICS
# Set the id, if you want to track your website with Google Analytics
# > set this to "", if you do not want to track with Google Analytics
google-analytics:
  id: "G-FZ3FLBCXCH"

### END OF VALUES YOU SHOULD CHANGE ###

plugins:
  - "jekyll-github-metadata"

exclude:
  [
    "_assets",
    "Gemfile",
    "Gemfile.lock",
    "gulpfile.js",
    "node_modules",
    "package.json",
  ]
